import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_excel("Global YouTube Statistics.xlsx")
df.columns = (df.columns.str.strip().str.lower().str.replace(" ", "_"))
df.dropna(how="all", inplace=True)
df["created_date"] = pd.to_datetime(df["created_date"], errors="coerce")
top_10_subs = df.sort_values(by="subscribers", ascending=False).head(10)
cat_avg_subs = df.groupby("category")["subscribers"].mean().sort_values(ascending=False)
cat_avg_uploads = df.groupby("category")["uploads"].mean().sort_values(ascending=False)
top_countries = df["country"].value_counts().head(5)
channel_type_dist = pd.crosstab(df["category"], df["channel_type"])
correlation_6 = df["subscribers"].corr(df["video_views"])
monthly_earnings_cat = df.groupby("category")[["lowest_monthly_earnings", "highest_monthly_earnings"]].mean()
plt.figure(figsize=(10, 5))
sns.histplot(df["subscribers_for_last_30_days"].dropna(), bins=50, kde=True)
plt.title("Distribution of Subscribers Gained in Last 30 Days")
plt.xlabel("Subscribers Gained")
plt.ylabel("Channel Count")
plt.show()
sns.boxplot(data=df[["lowest_yearly_earnings", "highest_yearly_earnings"]])
plt.title("Outliers in Yearly Earnings")
plt.show()
df["year_created"] = df["created_date"].dt.year
creation_trend = df["year_created"].value_counts().sort_index()
edu_country = df.groupby("country")["gross_tertiary_education_enrollment_(%)"].mean()
channels_country = df["country"].value_counts()
education_vs_channels = pd.DataFrame({"channels": channels_country,"education": edu_country}).dropna()
correlation_11 = education_vs_channels["channels"].corr(education_vs_channels["education"])
unemp_rate = df.groupby("country")["unemployment_rate"].mean()
top_10_unemp = unemp_rate.loc[top_countries.index]
urban_avg = df.groupby("country")["urban_population"].mean().mean()
plt.scatter(df["longitude"], df["latitude"], alpha=0.5)
plt.xlabel("Longitude")
plt.ylabel("Latitude")
plt.title("Geographic Distribution of YouTube Channels")
plt.show()
pop_corr = df["subscribers"].corr(df["population"])
top_10_population = df[df["country"].isin(top_countries.index)].groupby("country")["population"].mean()
corr_17 = df["subscribers_for_last_30_days"].corr(df["unemployment_rate"])
views_30_type = df.groupby("channel_type")["video_views_for_the_last_30_days"].mean()
seasonal_uploads = df.groupby(df["created_date"].dt.month)["uploads"].sum()
today = pd.to_datetime("today")
df["months_since_creation"] = ((today - df["created_date"]) / np.timedelta64(1, "M")).round(1)
df["avg_subs_per_month"] = df["subscribers"] / df["months_since_creation"]
avg_subs_per_month = df["avg_subs_per_month"].mean()
print("Top 10 Channels:\n", top_10_subs[["youtuber", "subscribers"]])
print("\nCategory with Highest Avg Subscribers:\n", cat_avg_subs.head(1))
print("\nAverage Uploads by Category:\n", cat_avg_uploads)
print("\nTop 5 Countries by Number of Channels:\n", top_countries)
print("\nChannel Type Distribution Across Categories:\n", channel_type_dist)
print("\nCorrelation (Subscribers vs Views):", correlation_6)
print("\nMonthly Earnings by Category:\n", monthly_earnings_cat)
print("\nCreation Trend (Year):\n", creation_trend)
print("\nCorrelation (Education vs Channels):", correlation_11)
print("\nUnemployment Rate in Top Countries:\n", top_10_unemp)
print("\nAverage Urban Population %:", urban_avg)
print("\nSubscribers vs Population Correlation:", pop_corr)
print("\nTop 10 Country Populations:\n", top_10_population)
print("\nCorrelation (Subs last 30d vs Unemp):", corr_17)
print("\nViews (30d) by Channel Type:\n", views_30_type)
print("\nSeasonal Upload Trend:\n", seasonal_uploads)
print("\nAverage Subscribers Gained Per Month:", avg_subs_per_month)
